mod commands;
mod models;
mod services;

use services::{PersistenceService, ProjectService, TerminalService};
use tauri_specta::{collect_commands, collect_events, Builder};
use tracing::info;
use tracing_subscriber::EnvFilter;

use crate::models::{TerminalDataEvent, TerminalExitEvent};

fn create_specta_builder() -> Builder {
    Builder::<tauri::Wry>::new()
        .commands(collect_commands![
            commands::project::list_projects,
            commands::project::add_project,
            commands::project::remove_project,
            commands::project::get_project,
            commands::terminal::create_terminal,
            commands::terminal::write_terminal,
            commands::terminal::resize_terminal,
            commands::terminal::close_terminal,
            commands::terminal::list_terminals,
            commands::workspace::load_workspace_state,
            commands::workspace::save_workspace_state,
        ])
        .events(collect_events![TerminalDataEvent, TerminalExitEvent])
}

pub fn export_bindings() {
    create_specta_builder()
        .export(
            specta_typescript::Typescript::default()
                .bigint(specta_typescript::BigIntExportBehavior::Number)
                .header("// @ts-nocheck\n// This file is auto-generated by specta. Do not edit.\n"),
            "../src/bindings.ts",
        )
        .expect("failed to export typescript bindings");
}

#[cfg_attr(mobile, tauri::mobile_entry_point)]
pub fn run() {
    tracing_subscriber::fmt()
        .with_env_filter(
            EnvFilter::try_from_default_env().unwrap_or_else(|_| EnvFilter::new("info")),
        )
        .init();

    let builder = create_specta_builder();

    // Export TypeScript bindings in debug mode
    #[cfg(debug_assertions)]
    export_bindings();

    info!("starting Mission Control");

    let persistence = PersistenceService::new();
    let project_service = ProjectService::new(PersistenceService::new());
    let terminal_service = TerminalService::new();

    tauri::Builder::default()
        .plugin(tauri_plugin_dialog::init())
        .invoke_handler(builder.invoke_handler())
        .setup(move |app| {
            builder.mount_events(app);
            Ok(())
        })
        .manage(persistence)
        .manage(project_service)
        .manage(terminal_service)
        .run(tauri::generate_context!())
        .expect("error while running tauri application");
}

#[cfg(test)]
mod tests {
    use super::*;

    #[test]
    fn export_typescript_bindings() {
        export_bindings();
    }
}
