mod commands;
mod models;
mod services;

use std::sync::{Arc, Mutex};

use services::{
    api_server, auth_gateway, hook_server, AgentService, AuthGateway, CredentialStore,
    FsWatcherService, GitService, PersistenceService, ProjectService, TerminalService,
};
use tauri::Manager;
use tauri_specta::{collect_commands, collect_events, Builder};
use tracing::info;
use tracing_subscriber::EnvFilter;

use crate::models::{
    AgentExitEvent, AgentOutputEvent, AgentStatusEvent, FsChangeEvent, GitRefChangedEvent,
    TerminalDataEvent, TerminalExitEvent,
};

fn create_specta_builder() -> Builder {
    Builder::<tauri::Wry>::new()
        .commands(collect_commands![
            commands::project::list_projects,
            commands::project::add_project,
            commands::project::remove_project,
            commands::project::get_project,
            commands::terminal::create_terminal,
            commands::terminal::write_terminal,
            commands::terminal::resize_terminal,
            commands::terminal::close_terminal,
            commands::terminal::list_terminals,
            commands::terminal::list_project_terminals,
            commands::terminal::get_terminal_scrollback,
            commands::terminal::restore_terminal,
            commands::workspace::load_workspace_state,
            commands::workspace::save_workspace_state,
            commands::fs::read_directory,
            commands::git::git_status,
            commands::git::git_log,
            commands::git::git_diff,
            commands::git::git_branches,
            commands::git::list_worktrees,
            commands::git::create_worktree,
            commands::git::remove_worktree,
            commands::git::create_checkpoint,
            commands::git::list_checkpoints,
            commands::git::rollback_to_checkpoint,
            commands::git::delete_checkpoint,
            commands::git::watch_project,
            commands::git::git_graph,
            commands::git::git_commit_detail,
            commands::agent::spawn_agent,
            commands::agent::stop_agent,
            commands::agent::resume_agent,
            commands::agent::write_agent,
            commands::agent::resize_agent,
            commands::agent::list_agents,
            commands::agent::get_agent,
            commands::agent::get_timeline,
            commands::credentials::list_credentials,
            commands::credentials::add_credential,
            commands::credentials::remove_credential,
            commands::credentials::get_gateway_status,
            commands::session::list_claude_sessions,
        ])
        .events(collect_events![
            TerminalDataEvent,
            TerminalExitEvent,
            FsChangeEvent,
            GitRefChangedEvent,
            AgentOutputEvent,
            AgentStatusEvent,
            AgentExitEvent
        ])
}

pub fn export_bindings() {
    create_specta_builder()
        .export(
            specta_typescript::Typescript::default()
                .bigint(specta_typescript::BigIntExportBehavior::Number)
                .header("// @ts-nocheck\n// This file is auto-generated by specta. Do not edit.\n"),
            "../src/bindings.ts",
        )
        .expect("failed to export typescript bindings");
}

#[cfg_attr(mobile, tauri::mobile_entry_point)]
pub fn run() {
    tracing_subscriber::fmt()
        .with_env_filter(
            EnvFilter::try_from_default_env().unwrap_or_else(|_| EnvFilter::new("info")),
        )
        .init();

    let builder = create_specta_builder();

    // Export TypeScript bindings in debug mode
    #[cfg(debug_assertions)]
    export_bindings();

    info!("starting Mission Control");

    // Primary persistence service — SQLite-backed with auto-migration from JSON
    let persistence = Arc::new(PersistenceService::new());
    let db_pool = persistence.db_pool().clone();

    // ProjectService gets its own persistence instance (same DB file, separate pool)
    let project_service = Arc::new(ProjectService::new(PersistenceService::new()));
    let terminal_service = TerminalService::new(Arc::clone(&persistence));
    let git_service = Arc::new(GitService::new());
    // Separate GitService instance for the hook server's auto-checkpoint feature
    let git_service_for_hooks = Arc::new(GitService::new());
    let fs_watcher_service = FsWatcherService::new();

    // Shared timeline between AgentService and HookServer
    let shared_timeline = Arc::new(Mutex::new(Vec::new()));
    let agent_service = Arc::new(AgentService::new(Arc::clone(&shared_timeline)));

    // Credential store — lives in a separate file from the main DB
    let cred_path = dirs::home_dir()
        .unwrap_or_else(|| std::path::PathBuf::from("."))
        .join(".mission-control")
        .join("credentials.bin");
    let credential_store = Arc::new(CredentialStore::new(cred_path));

    // Arc clones for the API server (created inside setup after hook_state & gateway exist)
    let api_project_service = Arc::clone(&project_service);
    let api_agent_service = Arc::clone(&agent_service);
    let api_git_service = Arc::clone(&git_service);

    tauri::Builder::default()
        .plugin(tauri_plugin_dialog::init())
        .invoke_handler(builder.invoke_handler())
        .setup(move |app| {
            builder.mount_events(app);

            // Start hook server for Claude Code hooks
            let app_handle = app.handle().clone();
            let hook_state = tauri::async_runtime::block_on(async {
                hook_server::start_hook_server(app_handle, Arc::clone(&shared_timeline), git_service_for_hooks)
                    .await
                    .expect("failed to start hook server")
            });

            // Start auth gateway for credential isolation
            let gateway = tauri::async_runtime::block_on(async {
                AuthGateway::start(
                    Arc::clone(&credential_store),
                    auth_gateway::default_auth_routes(),
                )
                .await
                .expect("failed to start auth gateway")
            });

            // Wrap hook_state and gateway in Arc for API server sharing
            let hook_state = Arc::new(hook_state);
            let gateway = Arc::new(gateway);

            // Start the REST API server on port 19420 (configurable via MC_API_PORT)
            let api_hook_state = Arc::clone(&hook_state);
            let api_gateway = Arc::clone(&gateway);
            tauri::async_runtime::block_on(async {
                api_server::start_api_server(
                    api_project_service,
                    api_agent_service,
                    api_git_service,
                    api_hook_state,
                    api_gateway,
                )
                .await
                .expect("failed to start API server")
            });

            // Manage Arc-wrapped types (shared with API server)
            app.manage(hook_state);
            app.manage(gateway);
            app.manage(credential_store);
            Ok(())
        })
        .manage(persistence)
        .manage(db_pool)
        .manage(project_service)
        .manage(terminal_service)
        .manage(git_service)
        .manage(fs_watcher_service)
        .manage(agent_service)
        .run(tauri::generate_context!())
        .expect("error while running tauri application");
}

#[cfg(test)]
mod tests {
    use super::*;

    #[test]
    fn export_typescript_bindings() {
        export_bindings();
    }
}
