// @ts-nocheck
// This file is auto-generated by specta. Do not edit.

// This file was generated by [tauri-specta](https://github.com/oscartbeaumont/tauri-specta). Do not edit this file manually.

/** user-defined commands **/


export const commands = {
async listProjects() : Promise<Result<Project[], AppError>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("list_projects") };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async addProject(name: string, path: string) : Promise<Result<Project, AppError>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("add_project", { name, path }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async removeProject(id: string) : Promise<Result<Project, AppError>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("remove_project", { id }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async getProject(id: string) : Promise<Result<Project, AppError>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("get_project", { id }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async createTerminal(projectId: string, cwd: string, cols: number, rows: number) : Promise<Result<TerminalInfo, AppError>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("create_terminal", { projectId, cwd, cols, rows }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async writeTerminal(id: string, data: number[]) : Promise<Result<null, AppError>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("write_terminal", { id, data }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async resizeTerminal(id: string, cols: number, rows: number) : Promise<Result<null, AppError>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("resize_terminal", { id, cols, rows }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async closeTerminal(id: string) : Promise<Result<null, AppError>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("close_terminal", { id }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async listTerminals() : Promise<Result<TerminalInfo[], AppError>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("list_terminals") };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async listProjectTerminals(projectId: string) : Promise<Result<TerminalInfo[], AppError>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("list_project_terminals", { projectId }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async getTerminalScrollback(id: string) : Promise<Result<number[], AppError>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("get_terminal_scrollback", { id }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async restoreTerminal(id: string, cols: number, rows: number) : Promise<Result<TerminalInfo, AppError>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("restore_terminal", { id, cols, rows }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async loadWorkspaceState() : Promise<Result<WorkspaceState, AppError>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("load_workspace_state") };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async saveWorkspaceState(state: WorkspaceState) : Promise<Result<null, AppError>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("save_workspace_state", { state }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async readDirectory(path: string) : Promise<Result<DirectoryEntry[], AppError>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("read_directory", { path }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async gitStatus(projectId: string, path: string) : Promise<Result<FileStatusEntry[], AppError>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("git_status", { projectId, path }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async gitLog(projectId: string, path: string, offset: number, limit: number) : Promise<Result<CommitInfo[], AppError>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("git_log", { projectId, path, offset, limit }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async gitDiff(projectId: string, path: string, oid: string) : Promise<Result<DiffInfo, AppError>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("git_diff", { projectId, path, oid }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async gitBranches(projectId: string, path: string) : Promise<Result<BranchInfo[], AppError>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("git_branches", { projectId, path }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async watchProject(projectId: string, path: string) : Promise<Result<null, AppError>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("watch_project", { projectId, path }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
}
}

/** user-defined events **/


export const events = __makeEvents__<{
fsChangeEvent: FsChangeEvent,
gitRefChangedEvent: GitRefChangedEvent,
terminalDataEvent: TerminalDataEvent,
terminalExitEvent: TerminalExitEvent
}>({
fsChangeEvent: "fs-change-event",
gitRefChangedEvent: "git-ref-changed-event",
terminalDataEvent: "terminal-data-event",
terminalExitEvent: "terminal-exit-event"
})

/** user-defined constants **/



/** user-defined types **/

export type AppError = { ProjectNotFound: string } | { ProjectAlreadyExists: string } | { TerminalNotFound: string } | { TerminalError: string } | { IoError: string } | { SerializationError: string } | { InvalidPath: string } | { GitError: string }
export type BranchInfo = { name: string; is_head: boolean; upstream: string | null; oid: string }
export type CommitInfo = { oid: string; short_oid: string; message: string; author: string; author_email: string; timestamp: number; parents: string[]; branch_refs: string[] }
export type DiffHunk = { header: string; lines: DiffLine[] }
export type DiffInfo = { commit_oid: string; files: FileDiff[]; stats: DiffStats }
export type DiffLine = { 
/**
 * "+" | "-" | " "
 */
origin: string; content: string; old_lineno: number | null; new_lineno: number | null }
export type DiffStats = { files_changed: number; insertions: number; deletions: number }
export type DirectoryEntry = { name: string; path: string; is_dir: boolean; is_hidden: boolean }
export type FileDiff = { path: string; 
/**
 * "added" | "modified" | "deleted" | "renamed"
 */
status: string; old_path: string | null; hunks: DiffHunk[] }
export type FileStatusEntry = { path: string; 
/**
 * "modified" | "staged" | "untracked" | "conflicted" | "deleted" | "renamed"
 */
status: string }
export type FsChangeEvent = { project_id: string; paths: string[] }
export type GitRefChangedEvent = { project_id: string }
export type Project = { id: string; name: string; path: string; created_at: string }
export type TerminalDataEvent = { terminal_id: string; data: number[] }
export type TerminalExitEvent = { terminal_id: string }
export type TerminalInfo = { id: string; project_id: string; title: string; cols: number; rows: number; cwd: string; created_at: string; status: string; scrollback_path: string | null }
export type WorkspaceState = { layout: string | null; active_project_id: string | null }

/** tauri-specta globals **/

import {
	invoke as TAURI_INVOKE,
	Channel as TAURI_CHANNEL,
} from "@tauri-apps/api/core";
import * as TAURI_API_EVENT from "@tauri-apps/api/event";
import { type WebviewWindow as __WebviewWindow__ } from "@tauri-apps/api/webviewWindow";

type __EventObj__<T> = {
	listen: (
		cb: TAURI_API_EVENT.EventCallback<T>,
	) => ReturnType<typeof TAURI_API_EVENT.listen<T>>;
	once: (
		cb: TAURI_API_EVENT.EventCallback<T>,
	) => ReturnType<typeof TAURI_API_EVENT.once<T>>;
	emit: null extends T
		? (payload?: T) => ReturnType<typeof TAURI_API_EVENT.emit>
		: (payload: T) => ReturnType<typeof TAURI_API_EVENT.emit>;
};

export type Result<T, E> =
	| { status: "ok"; data: T }
	| { status: "error"; error: E };

function __makeEvents__<T extends Record<string, any>>(
	mappings: Record<keyof T, string>,
) {
	return new Proxy(
		{} as unknown as {
			[K in keyof T]: __EventObj__<T[K]> & {
				(handle: __WebviewWindow__): __EventObj__<T[K]>;
			};
		},
		{
			get: (_, event) => {
				const name = mappings[event as keyof T];

				return new Proxy((() => {}) as any, {
					apply: (_, __, [window]: [__WebviewWindow__]) => ({
						listen: (arg: any) => window.listen(name, arg),
						once: (arg: any) => window.once(name, arg),
						emit: (arg: any) => window.emit(name, arg),
					}),
					get: (_, command: keyof __EventObj__<any>) => {
						switch (command) {
							case "listen":
								return (arg: any) => TAURI_API_EVENT.listen(name, arg);
							case "once":
								return (arg: any) => TAURI_API_EVENT.once(name, arg);
							case "emit":
								return (arg: any) => TAURI_API_EVENT.emit(name, arg);
						}
					},
				});
			},
		},
	);
}
